### ISSUE TITLE
Revamp UI

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/TurtleHurtles#1]
### Tasks
- [x] Manually download Possible Files instead of always downloading them
- [x] Downloading a new file adds it to Installed<type> automatically, no need to restart
- [x] Able to view available APIs/programs/testers to install from new UI
- [ ] Mouse support for advanced computers/turtles
- [ ] More intuitive terminal interaction. Ideas?
