### ISSUE TITLE
Proper Execution

### ISSUE THREAD

**Issue by FaceInCake** [FaceInCake/TurtleHurtles#2]
### Tasks
- [ ] Able to create shortcut programs in root dir that can be ran by the user instead of going through HurtleJumper
- [ ] When executing a program, unload APIs that were loaded by the program
- [ ] Intuitive function for loading other APIs
